server:
  port: 8888

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: git@github.com:kilopowq/config-server.git
#          strictHostKeyChecking: false
#          username: kilopowq
#          password: Kilopo_7520
##          skipSslValidation: true


spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
    consul:
      host: 172.17.0.1
      discovery:
        port: 8888
        prefer-ip-address: true
        instance-id: ${spring.application.name}:1
  profiles:
    active: native
