server:
  port: 8888


spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
    consul:
      host: 172.17.0.1
      discovery:
        port: 8888
        prefer-ip-address: true
        instance-id: ${spring.application.name}:1
  profiles:
    active: native
