server:
  port: 8081

spring:
  application:
    name: product-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: localhost
      discovery:
        port: 8081
        prefer-ip-address: true
        instance-id: ${spring.application.name}:1