server:
  port: 8083

spring:
  application:
    name: storefront-service
  cloud:
    consul:
      host: localhost
      discovery:
        port: 8083
        prefer-ip-address: true
        instance-id: ${spring.application.name}:1

kafka:
  server: localhost:9092
  producer:
    id: kilopo.event.producer

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

my:
  test:
    value: Newly refreshed hello from server local